name: azkar
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:



    sdk: flutter
  expansion_card: ^0.1.0

  audioplayers: ^0.14.0
  provider: ^4.1.3
  intl: ^0.16.1
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  auto_size_text: ^2.1.0

  firebase_messaging: ^6.0.1
  flutter_local_notifications: ^0.8.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/